### ISSUE TITLE
打开开发者模式不保留活动,startactivtyforresult 百分百失效

### ISSUE THREAD

**Issue by yizems** [Ifxcyr/ActivityMessenger#4]

**Comment by wuyr** [comment]
这个。。。。暂时还没有找到好的解决方案。

刚刚试了一下Github上的其他几个startActivityForResult的库，也是一样，失效了。
还有，我最后用原生的代码，直接重写了onActivityResult，也一样无效。

因为如果开了这个选项的话，在新的Activity启动之后，旧Activity就被Destroy了。

**Comment by yizems** [comment]
@wuyr 有效啊,我也试过的, 如果打开了开发者选项, onActivityResult 方法会在 onstart之后执行,
如果 singleTask,onNewIntent 也在 onStart之后执行的 都在onResume 方法之前

**Comment by wuyr** [comment]
等我消息。。。

**Comment by wuyr** [comment]
#### 经测试，发现在开启【不保留活动】时：
当目标*Activity*处理完任务，返回的时候，*发起者* 虽然也能重新回调`onCreate`、`onSaveInstanceState`和`onActivityResult`方法，但是！！！它已经不是原来的实例了！
也就是说，当目标*Activity*返回到上一级中，这时能看到的*Activity*，其实是通过反射重新创建的！并不是当初发起`startActivityForResult`时的对象了。
那个旧对象的`isDestroyed`会被标记为`ture`，已经没有利用价值了，如果这时候去做一些更新UI的操作，是徒劳的，但如果是做一些UI以外的操作比如说保存到数据库，这是可以的。

当然了，如果非要收到回调，可以复制下面的代码，把原来的`GhostFragment`给替换掉，就能正常运行了：
```kotlin
class GhostFragment : Fragment() {

    companion object {

        val fragmentDataStack: Stack<Triple<Int, Intent?, ((Intent?) -> Unit)>> = Stack()

        fun Context?.isAlwaysFinishActivity() = when {
            this == null -> false
            Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 -> Settings.Global.getInt(
                contentResolver,
                Settings.Global.ALWAYS_FINISH_ACTIVITIES,
                0
            ) != 0
            else -> false
        }
    }

    private var requestCode = -1
    private var intent: Intent? = null
    private var callback: ((result: Intent?) -> Unit)? = null

    fun init(requestCode: Int, intent: Intent, callback: ((result: Intent?) -> Unit)) {
        this.requestCode = requestCode
        this.intent = intent
        this.callback = callback
    }

    override fun onAttach(context: Context) {
        super.onAttach(context)
        if (context.isAlwaysFinishActivity()) {
            if (intent != null && callback != null) {
                fragmentDataStack.push(Triple(requestCode, intent!!, callback!!))
                intent = null
                callback = null
            }
            if (fragmentDataStack.isNotEmpty()) {
                val (requestCode, intent, callback) = fragmentDataStack.peek()
                intent?.let {
                    startActivityForResult(it, requestCode)
                    fragmentDataStack.pop()
                    fragmentDataStack.push(Triple(requestCode, null, callback))
                }
            }
        } else {
            intent?.let { startActivityForResult(it, requestCode) }
        }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        val result = if (resultCode == Activity.RESULT_OK && data != null) data else null
        if (context.isAlwaysFinishActivity()) {
            if (fragmentDataStack.isNotEmpty()) {
                val (srcRequestCode, _, callback) = fragmentDataStack.pop()
                if (requestCode == srcRequestCode) {
                    callback(result)
                }
            }
        } else {
            if (requestCode == this.requestCode) {
                callback?.let { it(result) }
            }
        }
    }

    override fun onDetach() {
        super.onDetach()
        intent = null
        callback = null
    }
}
```
替换了这段代码之后，虽然能收到回调，但是那个`callback`所对应的*Activity*实例，已经不是屏幕中显示的*Activity*了。
#### 修改的内容如下：
`startActivityForResult`之前先检查是否开启【不保留活动】，如果开启了，会把`intent`和`callback`放到一个静态的堆栈里面去，当*Activity*和*Fragment*在销毁后重新创建时，会把`callback`重新从堆栈里取出来，并执行回调。

**Comment by yizems** [comment]
思路很好，有两个可优化点

1 是不是保存 callback不应该是判断 不保留活动触发，而应该是 onsaveinstance触发，onrestore恢复
2 由于callback中引用的不是 以前的act实例，逻辑无法保证正确，可以在callback中 回传一个act实例，不再直接引用act中的属性或方法，恢复的时候改变act实例，这样就解决了实例不同引用的问题，但是这个没法检查，只能人为注意，比较尴尬，但是可以保证不会内存泄露，但是有个前提，数据一定要保存好，否则数据丢失一样会引起crash

话说我的生产环境，oppo vivo因为这个已经可以用crash蹦迪了

**Comment by wuyr** [comment]
1. 但是这两个方法是在*Activity*中重写的。。。作为一个库的话，很棘手，除非是手动在*Activity*中重写然后通知这个库，不过，这样做实在太麻烦了，甚至比直接用原生代码来写还麻烦。

 2. 其实引不引用*Activity*中的属性和方法，是取决于使用时的回调怎么写，库本身是不会去调用的。就像在*Activity*中开一个子线程去请求网络下载一个大文件，这时按HOME键，一段时间后如果*Activity*被销毁了，重新打开这个应用的时候（也就是新的实例），如果这时候刚刚下载文件的那个*Activity*刚好下载完成，通知更新UI的话，屏幕中正在显示的*Activity*也是不会更新UI的，因为两个*Activity*不是同一个对象，但是，可以通过`isDestroyed`去判断此*Activity*是否已被销毁。

啊，oppo和vivo这么叼的嘛，默认打开【不保留活动】？这个选项感觉只是为了照顾低端手机而出的，但是现在基本没有配置低到要开这个选项的手机了吧。。。

**Comment by yizems** [comment]
我感觉小米 vivo 和 oppo ,对于这种回收的机制很严格,说不上来为啥,手里的华为就没有出过这个问题,线上华为 的低端机报过几个错,但是也很少,小米+华为 是vivo+oppo 的crash 的 1/10 不到,以前我都没有处理过这种问题,现在有种遇上了天敌的感觉

**Comment by wuyr** [comment]
是啊，vivo oppo真的超级多兼容性问题的。。。用来做测试机就是找虐，开个USB调试都会定时关闭，有时候调试着就停了

**Comment by yizems** [comment]
小米华为加油,干掉 oppo vivo =.=
